
name: Build KrisWare
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build Jar
      run: ./gradlew clean build shadowJar || ./gradlew clean build

    - name: Find built JAR
      id: findjar
      run: |
        echo "JAR_PATH=$(find . -name '*.jar' | head -n 1)" >> $GITHUB_ENV

    - name: Upload Compiled Jar
      uses: actions/upload-artifact@v4
      with:
        name: KrisWare-Compiled
        path: ${{ env.JAR_PATH }}
