name: Build KrisWare (robust)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Try make gradlew executable (ignore if missing)
        run: |
          chmod +x ./gradlew || echo "gradlew missing, continuing without wrapper"

      - name: Build (use gradlew if present, otherwise install gradle and use it)
        run: |
          if [ -f "./gradlew" ]; then
            echo "Using project gradlew wrapper"
            ./gradlew clean build --no-daemon
          else
            echo "gradlew not found — installing gradle via sdkman (fallback)"
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.5 || true
            gradle clean build --no-daemon || true
          fi

      - name: Show built jars
        run: |
          echo "=== Searching for JARs ==="
          find . -type f -name "*.jar" -print || true

      - name: Find first built jar
        id: findjar
        run: |
          J=$(find . -type f -name "*.jar" | head -n 1 || true)
          echo "FOUND_JAR=$J"
          echo "FOUND_JAR=$J" >> $GITHUB_ENV

      - name: Upload Compiled Jar (if found)
        if: env.FOUND_JAR != ''
        uses: actions/upload-artifact@v4
        with:
          name: KrisWare-Compiled
          path: ${{ env.FOUND_JAR }}

      - name: Warn if nothing built
        if: env.FOUND_JAR == ''
        run: echo "Warning: No jar produced. Check build logs for failures."
