name: Build KrisWare

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Give Gradle permission
      run: chmod +x ./gradlew || echo "No gradlew file found"

    - name: Build all modules
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew clean build --no-daemon || true
        else
          echo "gradlew not found, initializing gradle..."
          gradle init || true
          gradle build || true
        fi

    - name: List built files
      run: ls -R build/libs || echo "No build/libs folder found"

    - name: Upload compiled jars
      uses: actions/upload-artifact@v4
      with:
        name: KrisWare-compiled
        path: '**/build/libs/*.jar'
        if-no-files-found: warn
